### ISSUE TITLE
Investigate assigning access roles for CP4NA UI users from the LDAP file

### ISSUE THREAD

**Issue by agopala95** [redhat-eets/cp4na#54]
Explore ways to pre-populate access roles (Automation Administrator, SLMAdmin, SPAdmin) for the default admin user of the CP4NA UI and other users such as almadmin in the file - https://github.com/redhat-eets/cp4na/blob/main/openldap/ldap-app.yaml.

**Comment by vjayaramrh** [comment]
The CP4NA UI comes up with default users (admin) and access roles that cannot be overriden as part of initial operator install via the ldap-app.yaml file. This issue can be closed with no further action needed.
